uploadprogress.lo: /home/ebounds/orca/sites/all/libraries/uploadprogress/uploadprogress.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ebounds/orca/sites/all/libraries/uploadprogress $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ebounds/orca/sites/all/libraries/uploadprogress/uploadprogress.c -o uploadprogress.lo 
$(phplibdir)/uploadprogress.la: ./uploadprogress.la
	$(LIBTOOL) --mode=install cp ./uploadprogress.la $(phplibdir)

./uploadprogress.la: $(shared_objects_uploadprogress) $(UPLOADPROGRESS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_uploadprogress) $(UPLOADPROGRESS_SHARED_LIBADD)

